apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mashroom-data
    namespace: default
spec:
    storageClassName: nfs
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 10Gi
